version: '3.8'

services:

  zeoserver:
    image: plone
    restart: always
    command: zeo
    volumes:
      - zeoserver:/data

  instance1:
    image: plone
    restart: always
    depends_on:
      - zeoserver
    ports:
      - "8081:8080"
    environment:
      ZEO_ADDRESS: zeoserver:8080

  instance2:
    image: plone
    restart: always
    depends_on:
      - zeoserver
    ports:
      - "8082:8080"
    environment:
      ZEO_ADDRESS: zeoserver:8080

volumes:
  zeoserver: {}
